### ISSUE TITLE
Unlocked Deposits not showing the right date

### ISSUE THREAD

**Issue by pxbee** [1Hive/tulip-frontend#86]
Deposits without a lock date should always say "Not locked"
![image.png](https://images.zenhubusercontent.com/601d877f631dd9fc7121c01c/d62bfc2f-971c-464e-8d70-1f4dda8ac290)

**Comment by danivega1912** [comment]
I cannot assign this issue to myself (have no permissions to do it) but I'll be taking a look over this issue.

**Comment by danivega1912** [comment]
This is fixed in https://github.com/1Hive/tulip-frontend/pull/88

**Comment by ceresbzns** [comment]
Fixed
